name: dpop
description: A pure Dart implementation of RFC 9449 (DPoP). Supports automatic proof generation, signing, and nonce retries for HTTP requests.
version: 0.1.1
repository: https://github.com/BruceJian43/dpop-dart

environment:
  sdk: ^3.10.0
  flutter: '>=3.24.0'

dependencies:
  http: ^1.6.0
  uuid: ^4.5.2
  webcrypto: ^0.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0

topics:
  - security
  - oauth
  - http
  - dpop